<?php

define("DISABLER_DOMAIN", trim(explode('.', $_SERVER['HTTP_HOST'])[0]));

//dsm('AH_SITE_ENVIRONMENT');

function tu_framework_mod_disable_cron() {
  //if (isset($_SERVER['HTTP_HOST'])) {}

  if (defined('DISABLER_DOMAIN')) {

    if (DISABLER_DOMAIN !== 'dev') {

      $modules = array(
      'bean_admin_ui',
      'context_ui',
      'devel',
      'feeds_admin_ui',
      'feeds_tamper_ui',
      'field_ui',
      'http_response_headers_ui',
      'rules_admin',
      'views_ui'
      );

      module_disable($modules, $disable_dependents = FALSE);
    }
  }
}
