<?php

/**
 * Disable and uninstall the modules listed in the $modules array.
 */

define("SUB_DOMAIN", trim(explode('.', $_SERVER['HTTP_HOST'])[0]));

//dsm('AH_SITE_ENVIRONMENT');



function tu_framework_mod_disable_cron() {
  //if (isset($_SERVER['HTTP_HOST'])) {}
  if (!defined('AH_SITE_ENVIRONMENT')){
    define('AH_SITE_ENVIRONMENT', SUB_DOMAIN); //this line is for testing purposes outside of acquia environments where AH_SITE_ENVIRONMENT may not be defined already
  }
  if (defined('AH_SITE_ENVIRONMENT')) {

    if (AH_SITE_ENVIRONMENT !== 'dev') {

      $modules = array(
      'bean_admin_ui',
      'context_ui',
      'devel',
      'feeds_admin_ui',
      'feeds_tamper_ui',
      'field_ui',
      'http_response_headers_ui',
      'rules_admin',
      'views_ui'
      );

      module_disable($modules, FALSE);
    }
  }
}
