<?php

$GLOBALS['modules_readable_name'] = array(
  //'bean_admin_ui' => 'Bean Admin UI',
  'context_ui' => 'Context UI',
  'devel' => 'Devel',
  'feeds_ui' => 'Feeds Admin UI',
  'feeds_tamper_ui' => 'Feeds Tamper UI',
  'field_ui' => 'Field UI',
  'http_response_headers_ui' => 'HTTP Response Headers UI',
  'rules_admin' => 'Rules Admin',
  'views_ui' => 'Views UI',
);

//define ldr as global with initial definition
